image/.* chafa %pistol-filename%
# Below does not work at the moment
# application/json fx %pistol-filename%
application/json.* sh: env FX_COLLAPSED=1 $(command -v fx) %pistol-filename%
# fpath .*.[mMdD]$ sh: $(command -v treemd) %pistol-filename%
application/javascript sh: env NVIM_APPNAME="nvim.light" $(command -v nvim) %pistol-filename%
text/.* sh: env NVIM_APPNAME="nvim.light" $(command -v nvim) %pistol-filename%
# text/* bat --paging=always --color=always %pistol-filename%
# text/* kak %pistol-filename%
# text/* mycustomvim %pistol-filename%
# text/* /usr/local/bin/vim -u NONE --not-a-term %pistol-filename%
# text/* /usr/local/share/vim/vim91/macros/less.sh %pistol-filename% < /dev/tty
