# backup usage: "rustic -P local backup
# cleanup:      "rustic -P local forget --prune
#
[repository]
repository =
"/media/change_me_username/change_me_deviceID/rustic-backups/passwords"
# password-file =  "/root/key-rustic"
no-cache = true # no cache needed for local repository
# password-command = "gpg --no-tty -q -d /etc/.rustic-pass.gpg"
password-command = "gpg -q -d --pinentry-mode loopback /etc/.rustic-pass.gpg"

[forget]
# keep-hourly = 20
# keep-daily = 14
keep-daily = 3
# keep-weekly = 8
# keep-monthly = 24
# keep-yearly = 10

[[backup.sources]]
source = "/home/change_me_username/passwords"
